Revert "Trial fixing undefined reference to WinMain@16 error (unsure if this will break the final .exe output)"
This reverts commit bf788e8c75e20110eef6b29be36f75f0fd8923c7.